### ISSUE TITLE
ImportError: No module named gco

### ISSUE THREAD

**Issue by aapatre** [thmoa/semantic_human_texture_stitching#31]
I'm using python2 in conda and getting the following error after running `bash run_sample.sh`

```
Step 1: make unwraps...
Traceback (most recent call last):
  File "step1_make_unwraps.py", line 16, in <module>
    from tex.texture import TextureData
  File "/media/ingnious/Acer/Users/nachi/repos/semantic_human_texture_stitching/tex/texture.py", line 10, in <module>
    from stitch.texels_fusion import Stitcher
  File "/media/ingnious/Acer/Users/nachi/repos/semantic_human_texture_stitching/stitch/texels_fusion.py", line 4, in <module>
    import gco
ImportError: No module named gco
Step 2: make priors...
Traceback (most recent call last):
  File "step2_segm_vote_gmm.py", line 6, in <module>
    import gco
ImportError: No module named gco
Step 3: stitch texture...
Traceback (most recent call last):
  File "step3_stitch_texture.py", line 14, in <module>
    from tex.texture import Texture
  File "/media/ingnious/Acer/Users/nachi/repos/semantic_human_texture_stitching/tex/texture.py", line 10, in <module>
    from stitch.texels_fusion import Stitcher
  File "/media/ingnious/Acer/Users/nachi/repos/semantic_human_texture_stitching/stitch/texels_fusion.py", line 4, in <module>
    import gco
ImportError: No module named gco

```

**Comment by aapatre** [comment]
Apologies, I skipped over the line which mentioned PyGCO:

`pip install gco-wrapper`
